# The publish directory is set to the root
[build]
  publish = "."

# Ensuring clean URLs

[[redirects]]
  from = "index.html"
  to = "/"
  status = 200
  
[[redirects]]
  from = "/*"
  to = "/:splat"
  status = 200