# The publish directory is set to the root
[build]
  publish = "."

[build.processing]
  html = true  # Enable clean URL processing
  
# Ensuring clean URLs
[[redirects]]
  from = "/*"
  to = "/:splat"
  status = 200